# secret (DB and RabbitMQ passwords)
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  db-pass: dnByb2RicGFzcw==    # vprodb root password (base64)
  rmq-pass: Z3Vlc3Q=           # RabbitMQ password (base64)